name: "Build Armbian"

on:
  workflow_dispatch:

jobs:
  build-armbian:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout build repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget git gcc make device-tree-compiler u-boot-tools \
                                  bc bison flex libssl-dev

      - name: Build Armbian image
        run: |
          ./compile.sh BOARD=orangepilite \
                         BRANCH=current \
                         RELEASE=resolute \
                         BUILD_DESKTOP=no \
                         BUILD_MINIMAL=yes \
                         KERNEL_CONFIGURE=no

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: armbian-image
          path: output/images/*.img.xz
